### ISSUE TITLE
About quickstart

### ISSUE THREAD

**Issue by mrwangyou** [bgin/Guided_Missile_Simulation#1]
Hi Bernard,

Thank you for your contributions to missile simulation. Honestly speaking, I've never seen anyone else in github who has more contributions than you do. 

I'm doing research about dogfight between planes. I want to adopt your GMS as missile model. I wonder if there is a quickstart file so that I can get to know how this architecture works? Thank you.

Best wishes

**Comment by bgin** [comment]
Hello @mrwangyou 

Thank you very much for your kind words.

Unfortunately the GMS project both Fortran and C++ versions are not finished yet.
Currently they constitute a bunch of different files still did not assembled into final
working solution,  hence there is not present a 'main' function.

The philosophy behind this project was and is to achieve as much possible realism as I'm able to do, hence
 many different [scientific] areas are being implemented, e.g  Radiolocation, Guidance.
Beside stated above I put a lot of effort in providing optimized code e.g. SIMD-Kernels (you shall have a look at this folder).

Best regards
Bernard Gingold

**Comment by bgin** [comment]
@mrwangyou 
Can I close the issue?

**Comment by mrwangyou** [comment]
@bgin Thank you for your reply. Sorry for just seeing your comment now. Wish your work will be finished successfully~~

**Comment by bgin** [comment]
Thank you very much.
